
# Базы данных
database:
  # БД с боссами
  file: "bosses_api.db"

# Настройки локализации
localization:
  # Файл локализации
  file: "ru_RU.yml"

# Боссы
# Это лишь конфиги
bosses:
  # Ключ босса
  # p.s Пример использования стиля, не работает ни с каким
  # боссом, так как он не зарегистрирован.
  angry_zombie:
    # Отображаемое имя босса.
    name: "Злобный Разбойник"

    # Максимальное здоровье.
    # Целое число (int).
    #
    # 1 - половина сердечка
    # 2 - целое сердечко
    health: 40

    # Базовый урон.
    # Дробное число (double).
    damage: 2.5

    # Конфигурация
    spawn:
      # Период появления босса в тиках.
      # Целое большее число (long).
      # Для спавна вручную установите значение -1
      #
      # Коммент по ТЗ: я не понял какое именно
      # время возрождения сделать, поэтому сделал появление
      # только через какое-то время.
      time: -1

      # При каком онлайне будет появляться босс.
      # Целое число (int).
      online: 1

      # Точка появления босса
      position:
        # Координата X.
        # Десятичное число (double).
        x: 0.0

        # Координата Y.
        # Десятичное число (double).
        y: 100.0

        # Координата Z.
        # Десятичное число (double).
        z: 0.0

        # Название активного мира (папки).
        world: "world"