# Боссы
# Это лишь конфиги
bosses:
  # Ключ босса
  # p.s Пример использования стиля, не работает ни с каким
  # боссом, так как он не зарегистрирован.
  angry_piglin:
    # Отображаемое имя босса.
    name: "Злобный Свин"

    # Максимальное здоровье.
    # Целое число (int).
    #
    # 1 - половина сердечка
    # 2 - целое сердечко
    health: 40

    # Базовый урон.
    # Дробное число (double).
    damage: 2.5

    # Конфигурация
    spawn:
      # Период появления босса в тиках.
      # Целое большее число (long).
      # Для спавна вручную установите значение -1
      #
      # Коммент по ТЗ: я не понял какое именно
      # время возрождения сделать, поэтому сделал появление
      # только через какое-то время.
      time: -1

      # При каком онлайне будет появляться босс.
      # Целое число (int).
      online: 1

      # Точка появления босса
      position:
        # Координата X.
        # Десятичное число (double).
        x: 0.0

        # Координата Y.
        # Десятичное число (double).
        y: 100.0

        # Координата Z.
        # Десятичное число (double).
        z: 0.0

        # Название активного мира (папки).
        world: "world"

  zombie_summoner:
    name: "&cПризыватель"
    health: 40
    damage: 2.5

    spawn:
      time: -1
      online: 1

      position:
        x: 0.0
        y: 100.0
        z: 0.0
        world: "world"

  pillager_ravager:
    name: "&cРазоритель"
    health: 40
    damage: 2.5

    spawn:
      time: -1
      online: 1

      position:
        x: 0.0
        y: 100.0
        z: 0.0
        world: "world"